### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by rawnly** [leonspok/Unsplash-Wallpaper#4]
Thats the error: 
```
Showing Recent Issues:
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

A screenshot here:
![schermata 2017-02-27 alle 19 53 16](https://cloud.githubusercontent.com/assets/16429579/23374898/7e295b78-fd26-11e6-9b59-11651b619f5b.png)

**Comment by huebnerob** [comment]
- You need to run a `pod install` before attempting to compile
- I've fixed another build issue with this PR: https://github.com/leonspok/Unsplash-Wallpaper/pull/5, you should now be able to build
